### ISSUE TITLE
vscode plugin falls on Repository indexing: reason - simlinks  

### ISSUE THREAD

**Issue by danilovmy** [forgoodaigithub/zencoder-vscode-plugin#2]
Error report:

"type": "Error",
"value": "ENOENT: no such file or directory, stat 'projectname\\static\\media\\simlink_to_other_folder_which_not_available"

Hi folks. I am trying to run the VScode plugin but it is not working. I have multiple symlinks in my repository, and not all sources were present when indexing the repository. The result is a plugin error.

p.s. i use  VScodium, windows 10, python/vuejs repository

**Comment by danilovmy** [comment]
attach error report
[error.json](https://github.com/user-attachments/files/17067414/error.json)

**Comment by iurii-iufimov-forgood** [comment]
Hi @danilovmy . Thank you for the report.

Can you please check your repo with plugin version `0.0.10` ?

**Comment by iurii-iufimov-forgood** [comment]
There was no answer. Closing the issue. Please report if the issue still exists.
