### ISSUE TITLE
zencoder chat error.

### ISSUE THREAD

**Issue by danilovmy** [forgoodaigithub/zencoder-vscode-plugin#3]
Vscode. After plugin install, choose command "Zencoder openchat".
Getting an error:
```
{
    "type": "Error",
    "value": "Chat ID is not provided",
    "stacktrace": { ... }
}
```

**Comment by iurii-iufimov-forgood** [comment]
@danilovmy , thanks for the report!
The issue is fixed in version `0.0.10`
